# Generated by Django 3.2.10 on 2023-08-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehicleDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vnumber', models.CharField(blank=True, max_length=15, null=True)),
                ('Vtype', models.CharField(blank=True, max_length=15, null=True)),
                ('Vmodel', models.CharField(blank=True, max_length=15, null=True)),
                ('Description', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
