# Generated by Django 3.2.10 on 2023-08-12 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicledb',
            old_name='Vmodel',
            new_name='Vehicle_Model',
        ),
        migrations.RenameField(
            model_name='vehicledb',
            old_name='Vnumber',
            new_name='Vehicle_Number',
        ),
        migrations.RenameField(
            model_name='vehicledb',
            old_name='Vtype',
            new_name='Vehicle_Type',
        ),
    ]
